// Code generated by "stringer -type=Capability"; DO NOT EDIT.

package providers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CanAutoDNSSEC-0]
	_ = x[CanConcur-1]
	_ = x[CanGetZones-2]
	_ = x[CanUseAKAMAICDN-3]
	_ = x[CanUseAlias-4]
	_ = x[CanUseAzureAlias-5]
	_ = x[CanUseCAA-6]
	_ = x[CanUseDHCID-7]
	_ = x[CanUseDNAME-8]
	_ = x[CanUseDS-9]
	_ = x[CanUseDSForChildren-10]
	_ = x[CanUseHTTPS-11]
	_ = x[CanUseLOC-12]
	_ = x[CanUseNAPTR-13]
	_ = x[CanUsePTR-14]
	_ = x[CanUseRoute53Alias-15]
	_ = x[CanUseRP-16]
	_ = x[CanUseSMIMEA-17]
	_ = x[CanUseSOA-18]
	_ = x[CanUseSRV-19]
	_ = x[CanUseSSHFP-20]
	_ = x[CanUseSVCB-21]
	_ = x[CanUseTLSA-22]
	_ = x[CanUseDNSKEY-23]
	_ = x[CanUseOPENPGPKEY-24]
	_ = x[DocCreateDomains-25]
	_ = x[DocDualHost-26]
	_ = x[DocOfficiallySupported-27]
	_ = x[CanUseAKAMAITLC-28]
}

const _Capability_name = "CanAutoDNSSECCanConcurCanGetZonesCanUseAKAMAICDNCanUseAliasCanUseAzureAliasCanUseCAACanUseDHCIDCanUseDNAMECanUseDSCanUseDSForChildrenCanUseHTTPSCanUseLOCCanUseNAPTRCanUsePTRCanUseRoute53AliasCanUseRPCanUseSMIMEACanUseSOACanUseSRVCanUseSSHFPCanUseSVCBCanUseTLSACanUseDNSKEYCanUseOPENPGPKEYDocCreateDomainsDocDualHostDocOfficiallySupportedCanUseAKAMAITLC"

var _Capability_index = [...]uint16{0, 13, 22, 33, 48, 59, 75, 84, 95, 106, 114, 133, 144, 153, 164, 173, 191, 199, 211, 220, 229, 240, 250, 260, 272, 288, 304, 315, 337, 352}

func (i Capability) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Capability_index)-1 {
		return "Capability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Capability_name[_Capability_index[idx]:_Capability_index[idx+1]]
}
